apiVersion: v1
kind: Service
metadata:
  name: builder-api
  namespace: workflowhub
  labels:
    app: builder-api
    app.kubernetes.io/name: builder-api
    app.kubernetes.io/component: api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:region:account-id:certificate/cert-id
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: builder-api
  sessionAffinity: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: builder-api
  namespace: workflowhub
  labels:
    app: builder-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: builder-api
  namespace: workflowhub
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: builder-api