[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "cp app/entry.server.node.tsx app/entry.server.tsx",
  "find app -name '*.ts*' -type f -exec sed -i 's/@remix-run\\/cloudflare/@remix-run\\/node/g' {} \\;",
  "NODE_ENV=production RAILWAY_ENVIRONMENT=production pnpm run build"
]

[start]
cmd = "node server-simple.js"