#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"

[vars]
# ANTHROPIC_API_KEY is set via Cloudflare dashboard or wrangler secret put
# Do not commit API keys to git
