apiVersion: v2
name: workflowhub
description: Enterprise Workflow Automation Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - workflow
  - automation
  - enterprise
  - no-code
home: https://workflowhub.io
sources:
  - https://github.com/workflowhub/workflowhub
maintainers:
  - name: WorkflowHub Team
    email: support@workflowhub.io
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: elasticsearch
    version: "8.x.x"
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: keycloak
    version: "18.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: keycloak.enabled