apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: workflowhub
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: workflowhub
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    name: http