apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflowhub
  labels:
    app: workflowhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflowhub
  template:
    metadata:
      labels:
        app: workflowhub
    spec:
      containers:
      - name: app
        image: workflowhub:production
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: workflowhub
spec:
  selector:
    app: workflowhub
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP