apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflowhub
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/workflowhub/workflowhub
    targetRevision: HEAD
    path: helm/workflowhub
    helm:
      valueFiles:
      - values.yaml
      - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: workflowhub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workflowhub
  namespace: argocd
spec:
  description: WorkflowHub Enterprise Platform
  sourceRepos:
  - 'https://github.com/workflowhub/*'
  destinations:
  - namespace: 'workflowhub*'
    server: https://kubernetes.default.svc
  - namespace: 'istio-system'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - name: admin
    policies:
    - p, proj:workflowhub:admin, applications, *, workflowhub/*, allow
    - p, proj:workflowhub:admin, repositories, *, *, allow
    groups:
    - workflowhub:admins
  - name: developer
    policies:
    - p, proj:workflowhub:developer, applications, get, workflowhub/*, allow
    - p, proj:workflowhub:developer, applications, sync, workflowhub/*, allow
    groups:
    - workflowhub:developers